### ISSUE TITLE
Token authentication doesn't update Access or Login time

### ISSUE THREAD

**Issue by lukewertz** [RESTful-Drupal/restful#662] opened 2015-09-30 13:37 UTC
Drupal keeps track of when users last logged in or accessed the site as a logged in user. They are properties on the user entity.

When using token authentication, I think that both the access and login times should be updated, but they are currently not updated.

I think of this as a bug, but am unsure if this is by design for some reason.

**Comment by amitaibu** [comment] 2015-09-30 13:39
Not by design. It should probably be updated, although with the access-token -- you'll have to update the user on every call, which might be a little too much

**Comment by lukewertz** [comment] 2015-09-30 13:42
This is a consequence, I think, of an implied feature. I don't think anyone designing a restful api would/should design a property that would be updated on every single call like the drupal access record is.

The login record is easy enough to maintain, but I'd love to know if you had any thoughts on the access record. Perhaps some type of throttled update on it? Perhaps it's a configuration that is exposed to site administrators and they have to manually enable?

For my use case, keeping track of the last login is sufficient and, as you indicate, I actively don't want to keep track of last-access because of the overhead with it.

**Comment by amitaibu** [comment] 2015-09-30 13:48
Since there's no cookie involved, there isn't really the notion of logged in, but rather "an action done by an authenticated user". 

Honestly, I'm not sure how to tackle this ;)

**Comment by lukewertz** [comment] 2015-09-30 14:14
Interesting. Your comment is making me think some more about this.

This all comes down to two of columns in drupal's `users` table: `access` and `login` which are timestamps. When we're talking about vanilla drupal functionality, I think those columns are updated thusly:
- `access` looks like it is handled by Drupal's [session handling](https://api.drupal.org/api/drupal/includes!session.inc/function/_drupal_session_write/7). (Interestingly, it also throttles the writes to the DB every 180 seconds.)
- `login` looks like it is handled by Drupal's user module in the function [user_login_finalize()](https://api.drupal.org/api/drupal/modules%21user%21user.module/function/user_login_finalize/7).

What this implies to me contradicts my earlier assertion regarding tracking login vs. access.

The concept of login time does seem to imply "logged into the drupal site" which is not what is happening when submitting a signed request via an API -- that is really "accessed the site as a credentialed user"

Given that, I'd be inclined to use the same logic that is in the _drupal_session_write function in a new method on the RESTful authentication handler.

```
    // Likewise, do not update access time more than once per 180 seconds.
    if ($user->uid && REQUEST_TIME - $user->access > variable_get('session_write_interval', 180)) {
      db_update('users')->fields(array(
        'access' => REQUEST_TIME,
      ))->condition('uid', $user->uid)->execute();
    }
```

**Comment by amitaibu** [comment] 2015-09-30 16:29
> Given that, I'd be inclined to use the same logic that is in the _drupal_session_write function in a new method on the RESTful authentication handler.

:+1:

**Comment by e0ipso** [comment] 2015-10-01 13:48
I agree with the conclusions of this thread. @lukewertz will you be able to tackle this PR?

Also, make sure to update the `{user}` table directly without `user_save` since that would probably cause cache stampedes.

**Comment by lukewertz** [comment] 2015-10-01 13:52
Yep. I should be able to get to it before Wednesday of next week.

Thanks.

**Comment by lukewertz** [comment] 2015-10-06 15:44
Here's a PR that adds this functionality: https://github.com/RESTful-Drupal/restful/pull/672

**Comment by e0ipso** [comment] 2015-10-20 12:15
Closing in favor of the existing PR.

**Closed as completed by e0ipso** 2015-10-20 12:15 UTC
